"""
Candidate shadow outcome provenance — neutral service module.

Owns the constants, taxonomy, and small pure helpers that govern how
candidate shadow outcomes are tagged, validated, and gated for
promotion eligibility. Extracted from web/api/edge_engine.py in PR-AD
commit 4 (Codex review): services should not depend on the web layer,
so the canonical source of truth for these values lives here.

Both web/api/edge_engine.py (which produces shadow outcomes via the
historical-backtest simulator) and services/recommendation_ledger.py
(which persists them) import from this module.

CRITICAL invariants (enforced by tests):
  - Only _tag_live_forward_observation may assign
    SAMPLE_PROVENANCE_FORWARD_POST_FREEZE to a record.
  - SAMPLE_PROVENANCE_HISTORICAL_REPLAY is NEVER in
    PROMOTION_ELIGIBLE_PROVENANCES.
  - is_promotion_eligible(record) fails closed on every uncertainty.

These invariants exist to prevent the in-sample-into-production
research-leakage failure mode that PR-AC/PR-AD were designed to
prevent.
"""
from __future__ import annotations

from typing import Any, Dict, Optional

import numpy as np


# ──────────────────────────────────────────────────────────────────────────
# Sample provenance taxonomy
# ──────────────────────────────────────────────────────────────────────────
#
# Tagged on every trade/recommendation record so the aggregator and
# promotion criteria can filter to genuinely out-of-sample evidence.
# Provenance is about HOW the data was collected, NOT WHEN. Re-running
# historical replay after PR-AD merges produces evidence that is still
# in-sample — the data was generated by the same code path used to
# discover the +14d rule.
#
# DEFENSIVE INVARIANT (enforced by source-grep regression tests): the
# only place that may assign SAMPLE_PROVENANCE_FORWARD_POST_FREEZE is
# `_tag_live_forward_observation` below, called exclusively from the
# live API path. Casual assignment from CLI flags, scripts, or
# downstream code is forbidden — otherwise someone could run
# historical replay with a "set provenance to forward" flag and
# recreate the leakage failure mode.

SAMPLE_PROVENANCE_HISTORICAL_REPLAY = "historical_replay_in_sample_or_research"
#   Output of scripts/replay_*.py or the historical-backtest simulator.
#   ALWAYS in-sample for the +14d rule (discovered on this exact
#   replay pipeline). NEVER promotion-eligible.

SAMPLE_PROVENANCE_FORWARD_POST_FREEZE = "forward_post_freeze"
#   Recommendation produced by the live engine in real time, against a
#   live chain, for an upcoming earnings event. Promotion-eligible
#   IFF created_at is after the PR-AD merge commit. ("Freeze" refers
#   to the rule being frozen at PR-AD; only post-freeze forward
#   observations count.) ASSIGNMENT IS RESTRICTED — only
#   _tag_live_forward_observation may write this value.

SAMPLE_PROVENANCE_HISTORICAL_HOLDOUT_PREREGISTERED = "historical_holdout_preregistered"
#   Escape hatch for a holdout set frozen BEFORE any analysis. NOT
#   USABLE TODAY. A string label is not enough — when this becomes a
#   real feature, it MUST require a frozen manifest artifact
#   (symbols + date ranges + content hash + author + timestamp
#   predating rule discovery). Until that infrastructure exists, this
#   constant is reserved but is NOT in PROMOTION_ELIGIBLE_PROVENANCES.

SAMPLE_PROVENANCE_UNKNOWN = "unknown"
#   Default fail-closed value. Never promotion-eligible. Used when the
#   caller did not explicitly tag provenance or when the tag was
#   invalid/non-canonical. Diagnostic aggregators SHOULD surface
#   UNKNOWN counts to maintain observability, but MUST NOT fold them
#   into promotion-eligible totals.

VALID_SAMPLE_PROVENANCES = frozenset({
    SAMPLE_PROVENANCE_HISTORICAL_REPLAY,
    SAMPLE_PROVENANCE_FORWARD_POST_FREEZE,
    SAMPLE_PROVENANCE_HISTORICAL_HOLDOUT_PREREGISTERED,
    SAMPLE_PROVENANCE_UNKNOWN,
})

# Promotion criteria reference this set. Any evidence outside it is
# NOT promotion-eligible regardless of magnitudes.
#
# DELIBERATELY ONLY ONE VALUE TODAY: HISTORICAL_HOLDOUT_PREREGISTERED
# is intentionally EXCLUDED until manifest verification exists. A
# string label is not a preregistration control.
PROMOTION_ELIGIBLE_PROVENANCES = frozenset({
    SAMPLE_PROVENANCE_FORWARD_POST_FREEZE,
})


def normalize_sample_provenance(value: Any) -> str:
    """Coerce *value* to a canonical sample_provenance string.

    Canonical inputs (members of VALID_SAMPLE_PROVENANCES) pass
    through unchanged. Anything else — None, typos, drift, unexpected
    types — collapses to SAMPLE_PROVENANCE_UNKNOWN.

    Codex P2 round-4: returning "unknown" instead of None preserves
    observability — invalid-provenance rows are visible in
    diagnostic counts under the UNKNOWN bucket, rather than silently
    disappearing as missing keys.
    """
    if isinstance(value, str) and value in VALID_SAMPLE_PROVENANCES:
        return value
    return SAMPLE_PROVENANCE_UNKNOWN


# ──────────────────────────────────────────────────────────────────────────
# Candidate shadow outcome — shape constants
# ──────────────────────────────────────────────────────────────────────────

_CANDIDATE_SHADOW_OUTCOME_FIELDS = (
    "side", "front_expiry", "back_expiry", "strike",
    "entry_front_mid", "entry_back_mid", "exit_front_mid", "exit_back_mid",
    "entry_front_iv", "entry_back_iv", "exit_front_iv", "exit_back_iv",
    "entry_debit_mid", "exit_value_mid", "mid_pnl",
    # Mid-pricing name embedded in the field so downstream aggregators
    # cannot quietly relabel this as an "execution return."
    "mid_realized_return_pct",
    "iv_change_front", "iv_change_back",
    # PR #64 (execution realism foundations): per-scenario debit /
    # exit / realized-return blocks. Each is a dict keyed by the
    # labels in services.execution_scenarios.SCENARIO_LEVELS — today
    # {"mid", "cross_25", "cross_50", "conservative"}. Values are
    # None when bid/ask coverage was insufficient to price that
    # scenario. The mid-only `mid_realized_return_pct` above is
    # preserved as the canonical research-grade number used by
    # `is_promotion_eligible` until the PR #65 gate refactor.
    "entry_scenario_values",
    "exit_scenario_values",
    "execution_scenario_returns_pct",
    "execution_scenario_pnl",
)

# Labels on every candidate_shadow_outcome block — communicate that the
# block is research-grade evidence only. Mid-based historical PnL is
# not execution-grade evidence.
_CANDIDATE_SHADOW_LABELS = {
    "research_mid": True,         # priced from mid, not bid/ask execution
    "shadow_only": True,          # never used as a trade signal
    "not_execution_grade": True,  # do not size live positions from this
}


# Scenario-block field names defined in PR #64. Listed separately
# from the scalar fields so `_empty_candidate_shadow_outcome` can
# stamp them as dict-shaped placeholders (not None scalars) and
# downstream consumers can always do `outcome["..."].get("cross_25")`
# without first None-checking the block itself.
_CANDIDATE_SHADOW_SCENARIO_BLOCK_FIELDS = frozenset({
    "entry_scenario_values",
    "exit_scenario_values",
    "execution_scenario_returns_pct",
    "execution_scenario_pnl",
})


def _empty_scenario_block() -> Dict[str, Optional[float]]:
    """Return a {label: None} placeholder covering every scenario in
    services.execution_scenarios.SCENARIO_LEVELS.

    Imported lazily inside the function to avoid circular imports —
    candidate_shadow_provenance is imported by execution_scenarios'
    own transitive consumers. The cost (one import per failure-path
    call) is negligible because failure paths run at most a few
    times per minute in production.
    """
    from services.execution_scenarios import SCENARIO_LEVELS
    return {name: None for name, _distance in SCENARIO_LEVELS}


def _empty_candidate_shadow_outcome(status: str) -> Dict[str, Any]:
    """Canonical empty candidate-shadow-outcome block.

    Used for every code path where the candidate picker's PnL cannot
    be resolved (no dual_picker, no candidate selection, missing
    quotes, non-positive debit, etc.). Stable shape so downstream
    consumers (aggregator, ledger schema) can rely on the same key
    set regardless of which failure path produced the record.

    Labels are ALWAYS present (research_mid / shadow_only /
    not_execution_grade) — they describe what kind of block this is,
    not whether it succeeded.

    PR #64: scenario-block fields are stamped as
    `{label: None}` dicts rather than scalar None, so consumers can
    `.get("cross_25")` without first None-checking the wrapper.
    """
    out: Dict[str, Any] = {"status": status, "labels": dict(_CANDIDATE_SHADOW_LABELS)}
    for k in _CANDIDATE_SHADOW_OUTCOME_FIELDS:
        if k in _CANDIDATE_SHADOW_SCENARIO_BLOCK_FIELDS:
            out[k] = _empty_scenario_block()
        else:
            out[k] = None
    return out


# ──────────────────────────────────────────────────────────────────────────
# Eligibility helpers
# ──────────────────────────────────────────────────────────────────────────

def is_promotion_eligible(record: Dict[str, Any]) -> bool:
    """Return True iff *record* is a fully-formed forward-validation
    observation that may contribute to candidate-vs-legacy promotion
    statistics.

    Fail-closed on every check. All of the following must hold:

      1. *record* is a dict.
      2. record["sample_provenance"] is in PROMOTION_ELIGIBLE_PROVENANCES.
         Today that's only SAMPLE_PROVENANCE_FORWARD_POST_FREEZE.
      3. record["candidate_shadow_outcome"] is a dict.
      4. candidate_shadow_outcome["status"] == "ok".
      5. candidate_shadow_outcome["mid_realized_return_pct"] is a
         finite number (rules out NaN/inf/string drift, and the
         bool-subclass-of-int gotcha).
      6. candidate_shadow_outcome["labels"] carries each of
         research_mid=True, shadow_only=True, not_execution_grade=True.

    This helper is the SINGLE source of truth for promotion
    eligibility. Aggregators, ledger queries, and promotion-criteria
    evaluation MUST route through it rather than open-coding partial
    checks.
    """
    if not isinstance(record, dict):
        return False
    if record.get("sample_provenance") not in PROMOTION_ELIGIBLE_PROVENANCES:
        return False
    outcome = record.get("candidate_shadow_outcome")
    if not isinstance(outcome, dict):
        return False
    if outcome.get("status") != "ok":
        return False
    pnl = outcome.get("mid_realized_return_pct")
    if not isinstance(pnl, (int, float)) or isinstance(pnl, bool):
        return False
    if not np.isfinite(pnl):
        return False
    labels = outcome.get("labels")
    if not isinstance(labels, dict):
        return False
    for required in ("research_mid", "shadow_only", "not_execution_grade"):
        if labels.get(required) is not True:
            return False
    return True


# ──────────────────────────────────────────────────────────────────────────
# Scenario-aware gate helpers (PR #66 visibility infrastructure)
# ──────────────────────────────────────────────────────────────────────────
#
# These helpers exist so the upcoming gate refactor (separate future PR)
# can consume execution-cost-aware evidence WITHOUT silently substituting
# mid for missing scenario values. PR #66 ships these helpers + the
# aggregator wiring that counts how often each scenario is actually
# priced; no production call site enables `allow_mid_fallback=True` in
# this PR. The flag exists so the future refactor can opt-in to a
# loudly-flagged transition mode, with `fallback_used=True` metadata
# making the substitution visible at every layer.
#
# Critical invariants enforced by tests:
#   - `is_promotion_eligible()` default behavior is byte-equivalent to
#     pre-PR-#66 (mid-only gate). Untouched.
#   - `candidate_return_for_gate()` is fail-closed by default. Missing
#     scenario → (None, metadata with missing_reason).
#   - `allow_mid_fallback=True` produces (mid_value, {fallback_used:
#     True, scenario_used: "mid"}) so any downstream aggregator can
#     count fallbacks without re-inspecting the outcome block.
#   - "conservative" is treated as an alias of "cross_50" throughout
#     so it never becomes an independent fourth stress dimension.


_SCENARIO_ALIASES = {
    # `conservative` is defined in execution_scenarios.SCENARIO_LEVELS
    # at distance=0.50 — exactly the same numerical contract as
    # cross_50. Today the simulator emits both keys with identical
    # values. Treating them as aliases at the gate-helper layer
    # prevents any future call site from creating a fourth evidence
    # bucket by querying both labels separately. If a future refactor
    # repoints `conservative` at a stricter cross (e.g. 0.75), this
    # alias mapping should be removed in the same commit and the
    # aggregator's scenario test list updated together.
    "conservative": "cross_50",
}


def _canonical_scenario_label(scenario: str) -> str:
    """Map alias labels (e.g. 'conservative') to their canonical
    counterpart (e.g. 'cross_50'). Unrecognized inputs pass through
    unchanged — validation is the caller's responsibility, since
    SCENARIO_LEVELS may change over time and we don't want this helper
    to be the source of "unknown scenario" error messages."""
    return _SCENARIO_ALIASES.get(scenario, scenario)


def candidate_return_for_gate(
    outcome: Optional[Dict[str, Any]],
    scenario: str,
    *,
    allow_mid_fallback: bool = False,
) -> tuple[Optional[float], Dict[str, Any]]:
    """Resolve the per-scenario realized return for promotion gating.

    Returns ``(value, metadata)`` where:

      * ``value`` is the finite per-scenario realized return (in
        percent) or ``None`` when the scenario could not be resolved
        and fallback was not opted in.

      * ``metadata`` is a stable-shape dict::

          {
            "scenario_requested": str,    # always the caller's input
            "scenario_used": str | None,  # what actually produced the
                                          # value: a canonical scenario
                                          # label, or "mid" on fallback,
                                          # or None on failure.
            "fallback_used": bool,        # True iff allow_mid_fallback
                                          # rescued an otherwise-missing
                                          # scenario value.
            "missing_reason": str | None, # None on success; one of the
                                          # codes below on failure.
          }

        Missing reasons (failure-only):

          - ``outcome_not_dict``      outcome arg was not a dict
          - ``outcome_status_not_ok`` outcome.status != "ok"
          - ``scenario_block_missing`` execution_scenario_returns_pct
                                      key absent from the outcome
          - ``scenario_value_absent`` requested scenario not in the
                                      block (caller used a label not
                                      in SCENARIO_LEVELS)
          - ``scenario_value_not_finite`` value present but NaN / inf
                                          / non-numeric / bool

    Fail-closed by default. ``allow_mid_fallback=False`` is the only
    behavior any current production caller uses (PR #66 ships no
    call site that flips this).

    When ``allow_mid_fallback=True`` and the requested scenario is
    missing-but-the-outcome-is-ok, this falls back to
    ``mid_realized_return_pct`` on the outcome and stamps
    ``fallback_used=True`` + ``scenario_used="mid"`` so downstream
    aggregators can count the substitution. This is the contract
    that lets a future gate refactor flip to scenario-aware gating
    while keeping a visible audit trail of how often missing-quote
    coverage drives the fallback path.
    """
    canonical = _canonical_scenario_label(scenario)

    meta: Dict[str, Any] = {
        "scenario_requested": scenario,
        "scenario_used": None,
        "fallback_used": False,
        "missing_reason": None,
    }

    if not isinstance(outcome, dict):
        meta["missing_reason"] = "outcome_not_dict"
        return None, meta
    if outcome.get("status") != "ok":
        meta["missing_reason"] = "outcome_status_not_ok"
        return None, meta

    scenario_block = outcome.get("execution_scenario_returns_pct")
    if not isinstance(scenario_block, dict):
        meta["missing_reason"] = "scenario_block_missing"
        return _maybe_mid_fallback(
            outcome, meta, allow_mid_fallback=allow_mid_fallback
        )

    if canonical not in scenario_block:
        meta["missing_reason"] = "scenario_value_absent"
        return _maybe_mid_fallback(
            outcome, meta, allow_mid_fallback=allow_mid_fallback
        )

    value = scenario_block.get(canonical)
    if (
        value is None
        or isinstance(value, bool)
        or not isinstance(value, (int, float))
        or not np.isfinite(value)
    ):
        meta["missing_reason"] = "scenario_value_not_finite"
        return _maybe_mid_fallback(
            outcome, meta, allow_mid_fallback=allow_mid_fallback
        )

    meta["scenario_used"] = canonical
    return float(value), meta


def _maybe_mid_fallback(
    outcome: Dict[str, Any],
    meta: Dict[str, Any],
    *,
    allow_mid_fallback: bool,
) -> tuple[Optional[float], Dict[str, Any]]:
    """Internal helper: route the failure path through mid-fallback
    when the caller opted in.

    The metadata dict is mutated in place — caller already populated
    `scenario_requested`, `missing_reason`. We add `scenario_used`
    and `fallback_used` only when the fallback successfully produces
    a finite mid value. Otherwise we return the failure as-is, so
    downstream observability sees the original missing_reason
    rather than a misleading "fallback also failed" cascade.
    """
    if not allow_mid_fallback:
        return None, meta

    mid_value = outcome.get("mid_realized_return_pct")
    if (
        mid_value is None
        or isinstance(mid_value, bool)
        or not isinstance(mid_value, (int, float))
        or not np.isfinite(mid_value)
    ):
        # Fallback requested but mid itself is unusable. Leave the
        # original missing_reason in place — it's more informative
        # than overwriting with "mid_also_missing".
        return None, meta

    meta["scenario_used"] = "mid"
    meta["fallback_used"] = True
    return float(mid_value), meta


def is_promotion_eligible_for_scenario(
    record: Dict[str, Any],
    scenario: str,
    *,
    allow_mid_fallback: bool = False,
) -> bool:
    """Scenario-aware variant of :py:func:`is_promotion_eligible`.

    Returns True iff BOTH:

      1. ``is_promotion_eligible(record)`` passes — i.e. the record
         already satisfies every existing strict criterion
         (provenance, outcome status, finite mid PnL, intact research
         labels). This dependency is deliberate so the new helper
         cannot accept a record the existing gate rejects.

      2. ``candidate_return_for_gate(outcome, scenario, ...)`` returns
         a finite value. With ``allow_mid_fallback=False`` (default)
         that means the scenario value itself must be priced;
         missing-bid/ask events fail this gate even if their mid
         path is fine.

    The new gate is strictly tighter than the old one when
    ``allow_mid_fallback=False`` and equivalent when
    ``allow_mid_fallback=True`` (modulo mid-priced events that pass
    the existing gate). It exists as a building block for a future
    promotion-policy change; PR #66 ships it as visibility plumbing
    only.
    """
    if not is_promotion_eligible(record):
        return False
    outcome = record.get("candidate_shadow_outcome")
    value, _meta = candidate_return_for_gate(
        outcome, scenario, allow_mid_fallback=allow_mid_fallback,
    )
    return value is not None


def _tag_live_forward_observation(record: Dict[str, Any]) -> Dict[str, Any]:
    """Tag *record* in-place with SAMPLE_PROVENANCE_FORWARD_POST_FREEZE.

    Underscore-prefixed: this is the ONLY function in the codebase
    authorized to assign the forward-post-freeze provenance value,
    and the leading underscore signals "module-private, do not import
    from outside this module."

    Intended call site: the live API path within edge_engine.py,
    after EdgeSnapshot construction and before record_recommendation.
    Historical replay code paths must never call this function —
    they emit HISTORICAL_REPLAY via the historical simulator's `base`
    dict.

    The source-grep regression test
    (TestForwardProvenanceAssignmentBoundary) scans services/ + web/ +
    scripts/ for any reference to this function name OR the underlying
    string literal, and fails if either appears outside this module
    or edge_engine.py.

    There is intentionally NO public alias — making the function
    appear "more importable" would defeat the assignment boundary.
    """
    record["sample_provenance"] = SAMPLE_PROVENANCE_FORWARD_POST_FREEZE
    return record
