"""
Candidate shadow outcome provenance — neutral service module.

Owns the constants, taxonomy, and small pure helpers that govern how
candidate shadow outcomes are tagged, validated, and gated for
promotion eligibility. Extracted from web/api/edge_engine.py in PR-AD
commit 4 (Codex review): services should not depend on the web layer,
so the canonical source of truth for these values lives here.

Both web/api/edge_engine.py (which produces shadow outcomes via the
historical-backtest simulator) and services/recommendation_ledger.py
(which persists them) import from this module.

CRITICAL invariants (enforced by tests):
  - Only _tag_live_forward_observation may assign
    SAMPLE_PROVENANCE_FORWARD_POST_FREEZE to a record.
  - SAMPLE_PROVENANCE_HISTORICAL_REPLAY is NEVER in
    PROMOTION_ELIGIBLE_PROVENANCES.
  - is_promotion_eligible(record) fails closed on every uncertainty.

These invariants exist to prevent the in-sample-into-production
research-leakage failure mode that PR-AC/PR-AD were designed to
prevent.
"""
from __future__ import annotations

from typing import Any, Dict, Optional

import numpy as np


# ──────────────────────────────────────────────────────────────────────────
# Sample provenance taxonomy
# ──────────────────────────────────────────────────────────────────────────
#
# Tagged on every trade/recommendation record so the aggregator and
# promotion criteria can filter to genuinely out-of-sample evidence.
# Provenance is about HOW the data was collected, NOT WHEN. Re-running
# historical replay after PR-AD merges produces evidence that is still
# in-sample — the data was generated by the same code path used to
# discover the +14d rule.
#
# DEFENSIVE INVARIANT (enforced by source-grep regression tests): the
# only place that may assign SAMPLE_PROVENANCE_FORWARD_POST_FREEZE is
# `_tag_live_forward_observation` below, called exclusively from the
# live API path. Casual assignment from CLI flags, scripts, or
# downstream code is forbidden — otherwise someone could run
# historical replay with a "set provenance to forward" flag and
# recreate the leakage failure mode.

SAMPLE_PROVENANCE_HISTORICAL_REPLAY = "historical_replay_in_sample_or_research"
#   Output of scripts/replay_*.py or the historical-backtest simulator.
#   ALWAYS in-sample for the +14d rule (discovered on this exact
#   replay pipeline). NEVER promotion-eligible.

SAMPLE_PROVENANCE_FORWARD_POST_FREEZE = "forward_post_freeze"
#   Recommendation produced by the live engine in real time, against a
#   live chain, for an upcoming earnings event. Promotion-eligible
#   IFF created_at is after the PR-AD merge commit. ("Freeze" refers
#   to the rule being frozen at PR-AD; only post-freeze forward
#   observations count.) ASSIGNMENT IS RESTRICTED — only
#   _tag_live_forward_observation may write this value.

SAMPLE_PROVENANCE_HISTORICAL_HOLDOUT_PREREGISTERED = "historical_holdout_preregistered"
#   Escape hatch for a holdout set frozen BEFORE any analysis. NOT
#   USABLE TODAY. A string label is not enough — when this becomes a
#   real feature, it MUST require a frozen manifest artifact
#   (symbols + date ranges + content hash + author + timestamp
#   predating rule discovery). Until that infrastructure exists, this
#   constant is reserved but is NOT in PROMOTION_ELIGIBLE_PROVENANCES.

SAMPLE_PROVENANCE_UNKNOWN = "unknown"
#   Default fail-closed value. Never promotion-eligible. Used when the
#   caller did not explicitly tag provenance or when the tag was
#   invalid/non-canonical. Diagnostic aggregators SHOULD surface
#   UNKNOWN counts to maintain observability, but MUST NOT fold them
#   into promotion-eligible totals.

VALID_SAMPLE_PROVENANCES = frozenset({
    SAMPLE_PROVENANCE_HISTORICAL_REPLAY,
    SAMPLE_PROVENANCE_FORWARD_POST_FREEZE,
    SAMPLE_PROVENANCE_HISTORICAL_HOLDOUT_PREREGISTERED,
    SAMPLE_PROVENANCE_UNKNOWN,
})

# Promotion criteria reference this set. Any evidence outside it is
# NOT promotion-eligible regardless of magnitudes.
#
# DELIBERATELY ONLY ONE VALUE TODAY: HISTORICAL_HOLDOUT_PREREGISTERED
# is intentionally EXCLUDED until manifest verification exists. A
# string label is not a preregistration control.
PROMOTION_ELIGIBLE_PROVENANCES = frozenset({
    SAMPLE_PROVENANCE_FORWARD_POST_FREEZE,
})


def normalize_sample_provenance(value: Any) -> str:
    """Coerce *value* to a canonical sample_provenance string.

    Canonical inputs (members of VALID_SAMPLE_PROVENANCES) pass
    through unchanged. Anything else — None, typos, drift, unexpected
    types — collapses to SAMPLE_PROVENANCE_UNKNOWN.

    Codex P2 round-4: returning "unknown" instead of None preserves
    observability — invalid-provenance rows are visible in
    diagnostic counts under the UNKNOWN bucket, rather than silently
    disappearing as missing keys.
    """
    if isinstance(value, str) and value in VALID_SAMPLE_PROVENANCES:
        return value
    return SAMPLE_PROVENANCE_UNKNOWN


# ──────────────────────────────────────────────────────────────────────────
# Candidate shadow outcome — shape constants
# ──────────────────────────────────────────────────────────────────────────

_CANDIDATE_SHADOW_OUTCOME_FIELDS = (
    "side", "front_expiry", "back_expiry", "strike",
    "entry_front_mid", "entry_back_mid", "exit_front_mid", "exit_back_mid",
    "entry_front_iv", "entry_back_iv", "exit_front_iv", "exit_back_iv",
    "entry_debit_mid", "exit_value_mid", "mid_pnl",
    # Mid-pricing name embedded in the field so downstream aggregators
    # cannot quietly relabel this as an "execution return."
    "mid_realized_return_pct",
    "iv_change_front", "iv_change_back",
    # PR #64 (execution realism foundations): per-scenario debit /
    # exit / realized-return blocks. Each is a dict keyed by the
    # labels in services.execution_scenarios.SCENARIO_LEVELS — today
    # {"mid", "cross_25", "cross_50", "conservative"}. Values are
    # None when bid/ask coverage was insufficient to price that
    # scenario. The mid-only `mid_realized_return_pct` above is
    # preserved as the canonical research-grade number used by
    # `is_promotion_eligible` until the PR #65 gate refactor.
    "entry_scenario_values",
    "exit_scenario_values",
    "execution_scenario_returns_pct",
    "execution_scenario_pnl",
)

# Labels on every candidate_shadow_outcome block — communicate that the
# block is research-grade evidence only. Mid-based historical PnL is
# not execution-grade evidence.
_CANDIDATE_SHADOW_LABELS = {
    "research_mid": True,         # priced from mid, not bid/ask execution
    "shadow_only": True,          # never used as a trade signal
    "not_execution_grade": True,  # do not size live positions from this
}


# Scenario-block field names defined in PR #64. Listed separately
# from the scalar fields so `_empty_candidate_shadow_outcome` can
# stamp them as dict-shaped placeholders (not None scalars) and
# downstream consumers can always do `outcome["..."].get("cross_25")`
# without first None-checking the block itself.
_CANDIDATE_SHADOW_SCENARIO_BLOCK_FIELDS = frozenset({
    "entry_scenario_values",
    "exit_scenario_values",
    "execution_scenario_returns_pct",
    "execution_scenario_pnl",
})


def _empty_scenario_block() -> Dict[str, Optional[float]]:
    """Return a {label: None} placeholder covering every scenario in
    services.execution_scenarios.SCENARIO_LEVELS.

    Imported lazily inside the function to avoid circular imports —
    candidate_shadow_provenance is imported by execution_scenarios'
    own transitive consumers. The cost (one import per failure-path
    call) is negligible because failure paths run at most a few
    times per minute in production.
    """
    from services.execution_scenarios import SCENARIO_LEVELS
    return {name: None for name, _distance in SCENARIO_LEVELS}


def _empty_candidate_shadow_outcome(status: str) -> Dict[str, Any]:
    """Canonical empty candidate-shadow-outcome block.

    Used for every code path where the candidate picker's PnL cannot
    be resolved (no dual_picker, no candidate selection, missing
    quotes, non-positive debit, etc.). Stable shape so downstream
    consumers (aggregator, ledger schema) can rely on the same key
    set regardless of which failure path produced the record.

    Labels are ALWAYS present (research_mid / shadow_only /
    not_execution_grade) — they describe what kind of block this is,
    not whether it succeeded.

    PR #64: scenario-block fields are stamped as
    `{label: None}` dicts rather than scalar None, so consumers can
    `.get("cross_25")` without first None-checking the wrapper.
    """
    out: Dict[str, Any] = {"status": status, "labels": dict(_CANDIDATE_SHADOW_LABELS)}
    for k in _CANDIDATE_SHADOW_OUTCOME_FIELDS:
        if k in _CANDIDATE_SHADOW_SCENARIO_BLOCK_FIELDS:
            out[k] = _empty_scenario_block()
        else:
            out[k] = None
    return out


# ──────────────────────────────────────────────────────────────────────────
# Eligibility helpers
# ──────────────────────────────────────────────────────────────────────────

def is_promotion_eligible(record: Dict[str, Any]) -> bool:
    """Return True iff *record* is a fully-formed forward-validation
    observation that may contribute to candidate-vs-legacy promotion
    statistics.

    Fail-closed on every check. All of the following must hold:

      1. *record* is a dict.
      2. record["sample_provenance"] is in PROMOTION_ELIGIBLE_PROVENANCES.
         Today that's only SAMPLE_PROVENANCE_FORWARD_POST_FREEZE.
      3. record["candidate_shadow_outcome"] is a dict.
      4. candidate_shadow_outcome["status"] == "ok".
      5. candidate_shadow_outcome["mid_realized_return_pct"] is a
         finite number (rules out NaN/inf/string drift, and the
         bool-subclass-of-int gotcha).
      6. candidate_shadow_outcome["labels"] carries each of
         research_mid=True, shadow_only=True, not_execution_grade=True.

    This helper is the SINGLE source of truth for promotion
    eligibility. Aggregators, ledger queries, and promotion-criteria
    evaluation MUST route through it rather than open-coding partial
    checks.
    """
    if not isinstance(record, dict):
        return False
    if record.get("sample_provenance") not in PROMOTION_ELIGIBLE_PROVENANCES:
        return False
    outcome = record.get("candidate_shadow_outcome")
    if not isinstance(outcome, dict):
        return False
    if outcome.get("status") != "ok":
        return False
    pnl = outcome.get("mid_realized_return_pct")
    if not isinstance(pnl, (int, float)) or isinstance(pnl, bool):
        return False
    if not np.isfinite(pnl):
        return False
    labels = outcome.get("labels")
    if not isinstance(labels, dict):
        return False
    for required in ("research_mid", "shadow_only", "not_execution_grade"):
        if labels.get(required) is not True:
            return False
    return True


def _tag_live_forward_observation(record: Dict[str, Any]) -> Dict[str, Any]:
    """Tag *record* in-place with SAMPLE_PROVENANCE_FORWARD_POST_FREEZE.

    Underscore-prefixed: this is the ONLY function in the codebase
    authorized to assign the forward-post-freeze provenance value,
    and the leading underscore signals "module-private, do not import
    from outside this module."

    Intended call site: the live API path within edge_engine.py,
    after EdgeSnapshot construction and before record_recommendation.
    Historical replay code paths must never call this function —
    they emit HISTORICAL_REPLAY via the historical simulator's `base`
    dict.

    The source-grep regression test
    (TestForwardProvenanceAssignmentBoundary) scans services/ + web/ +
    scripts/ for any reference to this function name OR the underlying
    string literal, and fails if either appears outside this module
    or edge_engine.py.

    There is intentionally NO public alias — making the function
    appear "more importable" would defeat the assignment boundary.
    """
    record["sample_provenance"] = SAMPLE_PROVENANCE_FORWARD_POST_FREEZE
    return record
